// <auto-generated />
using JornadaAHP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JornadaAHP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241112003756_NovaMigration")]
    partial class NovaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JornadaAHP.Models.Drive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Drives", (string)null);
                });

            modelBuilder.Entity("JornadaAHP.Models.Fonte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Fontes", (string)null);
                });

            modelBuilder.Entity("JornadaAHP.Models.Motor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("DriveId")
                        .HasColumnType("int");

                    b.Property<string>("Empresa")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("FonteId")
                        .HasColumnType("int");

                    b.Property<decimal>("ForcaMaxima")
                        .HasColumnType("DECIMAL");

                    b.Property<decimal>("ForcaMedia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR");

                    b.Property<decimal>("Peso")
                        .HasColumnType("DECIMAL");

                    b.Property<decimal>("Pontuacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Prazo")
                        .HasColumnType("INT");

                    b.Property<int>("RpmMaximo")
                        .HasColumnType("int");

                    b.Property<int>("RpmMedio")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DriveId");

                    b.HasIndex("FonteId");

                    b.ToTable("Motores", (string)null);
                });

            modelBuilder.Entity("JornadaAHP.Models.Pontuacao", b =>
                {
                    b.Property<decimal>("Pontos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Pontuacao");
                });

            modelBuilder.Entity("JornadaAHP.Models.Motor", b =>
                {
                    b.HasOne("JornadaAHP.Models.Drive", "Drive")
                        .WithMany("Motores")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JornadaAHP.Models.Fonte", "Fonte")
                        .WithMany("Motores")
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drive");

                    b.Navigation("Fonte");
                });

            modelBuilder.Entity("JornadaAHP.Models.Drive", b =>
                {
                    b.Navigation("Motores");
                });

            modelBuilder.Entity("JornadaAHP.Models.Fonte", b =>
                {
                    b.Navigation("Motores");
                });
#pragma warning restore 612, 618
        }
    }
}
